### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bug84** [Kartax/ioBroker.binance#15]
Hi, i had installed the adapter and every 10sec i become an error in logs.
How can i fix it?

![binance](https://user-images.githubusercontent.com/57953379/92227225-42262780-eea6-11ea-879b-86b90b433275.jpg)

**Comment by Kartax** [comment]
Hi could you give me some more information?

-  do you receive the error even on first request after you start the adapter?
- please provide a longer log (showing at what time the request has been sent)
- please provide your configuration (without the key and secret! )

**Comment by bug84** [comment]
The error appear every 10sec after updating price.
I only log BTC in the config![image](https://user-images.githubusercontent.com/57953379/92230751-eeb6d800-eeab-11ea-99b5-ed9c5c3e894a.jpeg)![image](https://user-images.githubusercontent.com/57953379/92230767-f2e2f580-eeab-11ea-84c4-1aa9ced53901.jpeg)

**Comment by Kartax** [comment]
Do you have configured a key & secret? If yo, please try and create a new instance of the adapter with a minimal configuration like this:
![image](https://user-images.githubusercontent.com/24891257/92246133-9db3dd80-eec5-11ea-9188-3f3bdb52e58e.png)

This configuration should work out of the box and only pull one price.
(the request of personal account data will be skipped)

**Comment by Kartax** [comment]
By the way, the intervall should not be set to 10s. permanentl. I suggest to use 2m instead  to avoid being blocked/banned by the binance api.
(However, i noticed a bug regarding that: If a 2m intervall is selected and saved, the ui sometimes still shows 10s as selected. One click on the dropwdown shows the correct value as selected)

**Comment by Kartax** [comment]
Any updates? I assume only requesting account-data fails.
Can you confirm that requesting 24hr data works without errors?

**Comment by bug84** [comment]
I don’t edit anything , and now I see that no error appear anymore. 
I don’t know why, but know it runs good with 10sec

**Comment by Kartax** [comment]
Hmm, ok. I will close this ticket - but thank you for your feedback!
